version: '3.8'

services:
  web:
    build: .
    container_name: web
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    ports:
      - "4200:80"
    networks:
      - my_network

networks:
  my_network:
    external: true
